on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    permissions:
      contents: write
    uses: ggsegverse/.github/.github/workflows/pkgdown.yaml@main
    with:
      use-chromote: true
      extra-packages: any::pkgdown, any::webshot2, any::chromote, local::.
